### ISSUE TITLE
点击全屏崩溃  偶现 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference

### ISSUE THREAD

**Issue by xujiweis** [xiaoyanger0825/NiceVieoPlayer#144]
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
  8169  8169 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:283)
--
18301-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:269)
18401-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.view.View.layout(View.java:20948)
18501-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6396)
18601-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
18701-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
18801-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
18901-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.view.View.layout(View.java:20948)
19001-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6396)
19101-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:331)
19201-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:269)
19301-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.view.View.layout(View.java:20948)
19401-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6396)
19501-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
19601-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
19701-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
19801-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.view.View.layout(View.java:20948)
19901-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6396)
20001-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:331)
20101-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:269)
20201-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1369)
20301-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.view.View.layout(View.java:20948)
20401-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6396)
20501-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2883)
20601-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2406)
20701-13 14:16:54.846  8169  8169 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1524)

**Comment by LinYiFa** [comment]
想请教下，这个问题您解决了嘛？什么原因呢？

**Comment by gaojian89** [comment]
@xiaoyanger0825 大佬能修复下这个问题吗？android10手机基本必现

**Comment by zouchanglin** [comment]
我也遇到了这个问题
