### ISSUE TITLE
android 4.2设备crash

### ISSUE THREAD

**Issue by XAndroidGay** [xiaoyanger0825/NiceVieoPlayer#20]
在android 4.2系统上切换小窗口时直接崩溃。log 如下：
 java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
E/AndroidRuntime( 3288): 	at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:237)
E/AndroidRuntime( 3288): 	at android.view.GLES20TextureLayer.setSurfaceTexture(GLES20TextureLayer.java:81)
E/AndroidRuntime( 3288): 	at android.view.HardwareRenderer$Gl20Renderer.setSurfaceTexture(HardwareRenderer.java:1576)
E/AndroidRuntime( 3288): 	at android.view.TextureView.getHardwareLayer(TextureView.java:393)
E/AndroidRuntime( 3288): 	at android.view.View.getDisplayList(View.java:12916)
E/AndroidRuntime( 3288): 	at android.view.View.getDisplayList(View.java:12997)
E/AndroidRuntime( 3288): 	at android.view.View.draw(View.java:13742)
E/AndroidRuntime( 3288): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3154)
E/AndroidRuntime( 3288): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3018)
E/AndroidRuntime( 3288): 	at android.view.View.draw(View.java:14049)
E/AndroidRuntime( 3288): 	at android.widget.FrameLayout.draw(FrameLayout.java:467)
E/AndroidRuntime( 3288): 	at android.view.View.getDisplayList(View.java:12953)
E/AndroidRuntime( 3288): 	at android.view.View.getDisplayList(View.java:12997)
E/AndroidRuntime( 3288): 	at android.view.View.draw(View.java:13742)
E/AndroidRuntime( 3288): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3154

**Comment by yuyuhan1** [comment]
该问题我也遇到了，网上也没有找到解决办法！
