### ISSUE TITLE
vivo Xplay5上播放异常

### ISSUE THREAD

**Issue by xiaobaicaiya** [xiaoyanger0825/NiceVieoPlayer#28]
07-10 17:11:16.242 24583-24583/? E/AgooFactory: init: mThreadPool = java.util.concurrent.ScheduledThreadPoolExecutor@3dc7850f[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
07-10 17:11:16.412 24006-24006/com.spreadit.spreaditapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.spreadit.spreaditapp, PID: 24006
                                                                          java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.spreadit.spreaditapp-1/base.apk", zip file "/data/app/com.spreadit.spreaditapp-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.spreadit.spreaditapp-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.spreadit.spreaditapp-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.spreadit.spreaditapp-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.spreadit.spreaditapp-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.spreadit.spreaditapp-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.spreadit.spreaditapp-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.spreadit.spreaditapp-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.spreadit.spreaditapp-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.spreadit.spreaditapp-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.spreadit.spreaditapp-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.spreadit.spreaditapp-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"
                                                                              at java.lang.Runtime.loadLibrary(Runtime.java:370)
                                                                              at java.lang.System.loadLibrary(System.java:988)
                                                                              at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:176)
                                                                              at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:187)
                                                                              at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:228)
                                                                              at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:224)
                                                                              at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:215)
                                                                              at com.xiao.nicevideoplayer.NiceVideoPlayer.initMediaPlayer(NiceVideoPlayer.java:362)
                                                                              at com.xiao.nicevideoplayer.NiceVideoPlayer.start(NiceVideoPlayer.java:176)
                                                                              at com.xiao.nicevideoplayer.TxVideoPlayerController.onClick(TxVideoPlayerController.java:352)
                                                                              at android.view.View.performClick(View.java:4785)
                                                                              at android.view.View$PerformClick.run(View.java:19919)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5413)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:927)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:722)
07-10 17:11:17.672 19690-19709/? E/LockboxBrokerService: Could not query UDC's getDeviceDataUploadOptInStatus; 15 null

**Comment by xiaobaicaiya** [comment]
补充 android 5.1.1

**Comment by xiaobaicaiya** [comment]
@xiaoyanger0825

**Comment by xiaoyanger0825** [comment]
hello，我刚刚用vivo Xplay5测试了一下，没有报错呢，我这边系统是6.0，你那边是直接运行就会有这个错误吗？

**Comment by xiaobaicaiya** [comment]
@xiaoyanger0825 我在别的手机上没啥问题  ，但是在这边我也不晓得什么情况，初始化设置完成  然后代码：
  private void initVideovie() {
        mNiceVideoPlayer.setUp("http://tanzi27niu.cdsb.mobi/wps/wp-content/uploads/2017/05/2017-05-17_17-33-30.mp4", null);
        TxVideoPlayerController controller = new TxVideoPlayerController(this);
        controller.setTitle("办公室小野开番外了，居然在办公室开澡堂！老板还点赞？");
        controller.setLenght(98000);
        Glide.with(this)
                .load("http://tanzi27niu.cdsb.mobi/wps/wp-content/uploads/2017/05/2017-05-17_17-30-43.jpg")
                .placeholder(R.drawable.img_default)
                .crossFade()
                .into(controller.imageView());
        mNiceVideoPlayer.setController(controller);
    }

    @Override
    protected void onStop() {
        if(mNiceVideoPlayer.isPlaying()){
            playingFlag=true;
        }else{
            playingFlag=false;
        }
        // 在OnStop中是release还是suspend播放器，需要看是不是因为按了Home键
        if (pressedHome) {
            NiceVideoPlayerManager.instance().suspendNiceVideoPlayer();
        } else {
            NiceVideoPlayerManager.instance().releaseNiceVideoPlayer();
        }
        super.onStop();
        mHomeKeyWatcher.stopWatch();
    }
    @Override
    protected void onRestart() {
        mHomeKeyWatcher.startWatch();
        pressedHome = false;
        super.onRestart();
        NiceVideoPlayerManager.instance().resumeNiceVideoPlayer();
    }
进去以后点击播放 就异常了

**Comment by xiaoyanger0825** [comment]
试着重新编译一下呢，有可能是so包掉了

**Comment by xiaobaicaiya** [comment]
还是一样的

**Comment by xiaoyanger0825** [comment]
我下个版本试着不直接在gradle添加ijk的so的依赖了，直接报so包放lib文件夹下。你可以先试一下去编译出so包直接放到lib文件加下，因为我目前是没有添加64位的so的依赖的，因为64的依赖需要最低api21

**Comment by shimiso** [comment]
不要用自己编译的so库,用官方的
   //required, enough for most devices.
    compile 'tv.danmaku.ijk.media:ijkplayer-java:0.8.2'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.8.2'
    //Other ABIs: optional
    compile 'tv.danmaku.ijk.media:ijkplayer-armv5:0.8.2'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.8.2'
