### ISSUE TITLE
小窗口播放崩溃

### ISSUE THREAD

**Issue by bozhai** [xiaoyanger0825/NiceVieoPlayer#6]
场景：播放－小窗口播放－切出去－再次进入app－小窗口点击播放－右下角出现全屏按钮－点击全屏－崩溃
1. 小窗口播放 不能切回道原始播放状态么？
谢谢！
以下是log信息
06-13 21:20:24.135 25020-25020/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.xiao.nicevieoplayer, PID: 25020
                                                   java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                       at android.view.ViewGroup.addViewInner(ViewGroup.java:4654)
                                                       at android.view.ViewGroup.addView(ViewGroup.java:4490)
                                                       at android.view.ViewGroup.addView(ViewGroup.java:4462)
                                                       at com.xiao.nicevideoplayer.NiceVideoPlayer.enterFullScreen(NiceVideoPlayer.java:422)
                                                       at com.xiao.nicevideoplayer.NiceVideoPlayerController.onClick(NiceVideoPlayerController.java:143)
                                                       at android.view.View.performClick(View.java:5697)
                                                       at android.view.View$PerformClick.run(View.java:22526)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:158)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by xiaoyanger0825** [comment]
目前暂时不支持直接从小窗口到全屏，后续会做处理

**Comment by xiaoyanger0825** [comment]
@bozhai 已发新版，支持直接从小窗口到全屏
